name: Build and Deploy

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: The branch name, tag, or commit SHA to check out.
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: '**/package.json'
          node-version-file: package.json
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Artifact
        run: npm run build
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
